import { ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { Roboto } from "next/font/google";
import "./globals.css";
import ClientLayout from "./ClientLayout";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const roboto = Roboto({
//   subsets: ["latin"], // Subset bahasa, 'latin' umum digunakan
//   variable: "--font-roboto", // Nama variabel CSS kustom untuk font ini
// });

export const metadata: Metadata = {
  title: "OmToekang",
  description: "Generated by create-flowbite-react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
